### ISSUE TITLE
⚙️ [수정사항] 프로젝트 구조 통일

### ISSUE THREAD

**Issue by atto08** [jiminchur/Project_FoodToGoWeb#83]
## ❗️ 현재상황
* 현도님 : 파일, 패키지명 -> 단수
* 민철님 : 파일, 패키지명 -> 복수

**Comment by jiminchur** [comment]
## 🛠️ 수정사항
* 민철
  * 그동안 개발했던 Restaurant, Restaurant Category 패키지 안에 있는 패키지 및 파일명을 수정해서 dev-mono에 merge 했습니다.
* 수정했던 merge 요청번호 #89 입니다.
